sudo: required

env:
  - distribution: ubuntu
  - distribution: fedora
  - distribution: arch
  - distribution: debian-testing
  - distribution: debian

services:
  - docker

before_install:
  - ./ci/update_ci.sh

script:
  - script=static_analysis ./ci/execute.sh
  - script=clean ./ci/execute.sh
  - script=compile CXX=g++ CC=gcc ./ci/execute.sh
  - script=compile make_command="CTEST_OUTPUT_ON_FAILURE=1 make test" ./ci/execute.sh
